# Generated by Django 2.1.2 on 2018-10-27 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeforgood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='accessbility',
            new_name='accessibility',
        ),
        migrations.AlterField(
            model_name='locations',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeforgood.Users'),
        ),
    ]
