# Generated by Django 2.1.2 on 2018-10-28 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeforgood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='coords',
            new_name='place',
        ),
    ]
