# Generated by Django 2.1.2 on 2018-10-27 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeforgood', '0002_auto_20181027_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('accessibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='locations',
            name='accessibility',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='tags',
        ),
        migrations.AddField(
            model_name='location_tags',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforgood.Tags'),
        ),
        migrations.AddField(
            model_name='location_tags',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforgood.Locations'),
        ),
    ]
