# Generated by Django 2.1.2 on 2018-10-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeforgood', '0003_auto_20181027_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='favourite_loc_id',
            new_name='favourite_loc',
        ),
        migrations.RenameField(
            model_name='favourites',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='location_tags',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='location_tags',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='saved_searches',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='suggestions',
            old_name='loc_id',
            new_name='loc',
        ),
        migrations.RenameField(
            model_name='suggestions',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='warnings',
            old_name='loc_id',
            new_name='loc',
        ),
    ]
