# Generated by Django 2.1.2 on 2018-10-27 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeforgood', '0004_auto_20181027_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_tags',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforgood.Locations'),
        ),
        migrations.AlterField(
            model_name='location_tags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeforgood.Tags'),
        ),
    ]
